### ISSUE TITLE
issue while running start-spark-shell.sh

### ISSUE THREAD

**Issue by sbcd90** [SAP/HANAVora-Extensions#2]
Hello,

the spark shell starts correctly on executing the script `start-spark-shell.sh`.
But once I run the command `sqlContext.sql("show tables").show` I get the error

`java.lang.RuntimeException: Stream '/jars/*.jar' was not found.`. Can someone help plz?

Kindly note, I just compiled the project & ran the .sh file in dist.

**Comment by stephankessler** [comment]
Hi sbcd90 :)

those shell scripts are rather for packaging in the distribution tar.gz and not for the direct execution. You should find the tar.gz file in the target folder of the `dist` module.

If you extract that, scripts are included and will work.

Best,
Stephan

**Comment by sbcd90** [comment]
Thanks. That worked.
Just a small question. Do you allow external contributions?

**Comment by stephankessler** [comment]
Sure! In most of the cases it makes sense to just open an issue on what you plan to change, then we can quickly discuss and bring a PR in!

Thanks!
