### ISSUE TITLE
Issue with append data command 

### ISSUE THREAD

**Issue by sbcd90** [SAP/HANAVora-Extensions#3]
Hello,

I tried executing the following command

`%vora APPEND TABLE EMPLOYEE OPTIONS (paths "hdfs://localhost:9000/tmp/SHA_Employee_append.csv", eagerLoad "true")`

& I got the following error

`Error: com.sap.spark.hana.HANARelation cannot be cast to org.apache.spark.sql.sources.AppendRelation`

Kindly note, the basic commands like read/write to hana works fine still for me.
Can somebody help?

Thanks & regards,
Subhobrata

**Comment by stephankessler** [comment]
Hi Subhobrata,

the append command has to be supported by the datasource, this is not the case for the HANA datasource (while it is for the Vora one) - so this won't work.

If you want do pass data back to hana, you have to write or insert as usual.

Does this answer your question?

Best,
Stephan

**Comment by sbcd90** [comment]
Thanks. Yes. That answers my question.
