### ISSUE TITLE
Unable to execute start-spark-shell.sh from Mac

### ISSUE THREAD

**Issue by ramnivas** [SAP/HANAVora-Extensions#5]
After getting a distribution built (see #4), I couldn't get start-spark-shell.sh working from my Mac (due to `readlink` being not available by default on Mac).

```
[bin] ./start-spark-shell.sh 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
[ERROR] too many jar files in 
[ERROR] please check your installation
```

Installing `greadlink` (via `brew install coreutils`) moved things forward a bit, but met with another error:
```
[bin] ./start-spark-shell.sh 
[ERROR] too many jar files in /Users/ramnivas/dev/vora/dist/lib
[ERROR] please check your installation
```

I verified that there is only one file in the `lib` directory.

For now, I am able to workaround by executing:
```
$ spark-shell.sh --jars <path to spark-sap-parent-1.3.69-assembly.jar or core-1.3.69.jar>
```
which seems like what the start-spark-shell.sh does effectively anyway.

**Comment by burgerdev** [comment]
The workaround is in fact what the script does, should be safe to use. I will have a look into that issue.
