### ISSUE TITLE
Failed to find data source: com.sap.spark.vora

### ISSUE THREAD

**Issue by ramnivas** [SAP/HANAVora-Extensions#6]
After working through #4 and #5, I am running into another problem.

```scala
scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> val sqlc = new SapSQLContext(sc)
sqlc: org.apache.spark.sql.SapSQLContext = org.apache.spark.sql.SapSQLContext@221ec884

scala>sqlc.sql("""CREATE TABLE people (name string, age int) USING com.sap.spark.vora OPTIONS (files "path-to/test.json") """)
java.lang.ClassNotFoundException: Failed to find data source: com.sap.spark.vora. Please find packages at http://spark-packages.org
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:77)
	at org.apache.spark.sql.DefaultDatasourceResolver.lookup(DatasourceResolver.scala:74)
...
```

Note that I am starting the spark-shell as described in the workaround for #5 

Here are the versions I am using:
Spark: 1.6.1 (with hadoop 2.6)
Scala: 2.10.5
Java: 1.8.0_51

**Comment by MrManz** [comment]
I have the same problem when deploying a application as jar

**Comment by burgerdev** [comment]
The datasource provider `com.sap.spark.vora` is not part of this project. It is supplied as part of [http://go.sap.com/product/data-mgmt/hana-vora-hadoop.html|SAP HANA Vora].

**Comment by ramnivas** [comment]
@burgerdev Thanks for clarifying.
