### ISSUE TITLE
object SapSQLcontext is not a member of org.apache.sql.SQLcontext

### ISSUE THREAD

**Issue by jyoti-264** [SAP/HANAVora-Extensions#8]
Hi,

Getting error "object SapSQLcontext is not a member of org.apache.sql.SQLcontext" when running the command "import org.apache.spark.sql.SapSQLContext". 

Please suggest.

![error](https://cloud.githubusercontent.com/assets/21688965/18175014/57486c86-708d-11e6-8a44-786fc334e5e8.jpg)

Thanks,
Jyoti

**Comment by ramnivas** [comment]
You need to invoke the spark shell as mentioned in #5 
```
$ spark-shell.sh --jars <path to spark-sap-parent-1.3.69-assembly.jar or core-1.3.69.jar>
```

**Comment by jyoti-264** [comment]
I get following response:'

![error](https://cloud.githubusercontent.com/assets/21688965/18193114/f78a4f38-70f7-11e6-9ffb-6a0e344b5bf0.jpg)

**Comment by burgerdev** [comment]
Hi Jyoti,

the argument for option `--jars` is supposed to be a regular file and should be something similar to `spark-sap-parent-1.3.69-assembly.jar`. Did you build the jar file already?

Cheers, Markus

**Comment by jyoti-264** [comment]
Thankyou all for your inputs. I was not using correct .jar files to invoke spark :)
